#pragma once
#include "error_code.h"
#include "info_code.h"

enum class OP_TYPE { SEND, RECV, ACCEPT, DB, DELETE_ROOM };

enum class DBOperationType { LOGIN, LOAD_SESSION_INFO, UPDATE_SCORE, UPDATE_MATCH_RESULT, LOAD_MATCH_RECORD, DB_ERROR };

enum class ROOM_USER_STATE { EMPTY, WAIT, READY, PLAY, GAMEOVER };

enum class ROOM_STATE { EMPTY, WAIT, PLAY, WAITING_DELETE };

enum class SESS_STATE { NONE, LOGIN, LOBBY, ROOM, WAIT };

enum class EVENT_TYPE { NONE = -1, RIGHT, LEFT, ROTATE, DOWN, DROP, UP, MOVE, FIX, CLEARLINE, ADDLINE, GAMEOVER, GAMEEND, SPAWN };