#pragma once

enum class OP_TYPE { SEND, RECV, ACCEPT, DB };

enum class DBOperationType { LOGIN, LOAD_SESSION_INFO, SCORE_UPDATE, DB_ERROR };

enum class ROOM_USER_STATE { EMPTY, WAIT, READY, PLAY, GAMEOVER };

enum class ROOM_STATE { EMPTY, WAIT, PLAY };

enum class USER_STATE { NONE, LOGIN, LOBBY, ROOM };

enum class EVENT_TYPE { NONE = -1, RIGHT, LEFT, ROTATE, DOWN, DROP, UP, MOVE, FIX, CLEARLINE, ADDLINE, GAMEOVER };