#pragma once
#include "error_code.h"
#include "info_code.h"

enum class OPType { SEND, RECV, ACCEPT, DB, DELETE_ROOM};

enum class DBOperationType { LOGIN, LOAD_SESSION_INFO, LOAD_RANKING, UPDATE_SCORE, UPDATE_MATCH_RESULT, 
							ADD_FRIEND, DELETE_FRIEND, ADD_FRIEND_REQUEST, DELETE_FRIEND_REQUEST, GET_FRIEND_INFO, LOAD_FRIEND_LIST, LOAD_MATCH_RECORD, DB_ERROR };

enum class RoomUserState { EMPTY, WAIT, READY, PLAY, GAMEOVER };

enum class RoomState { EMPTY, WAIT, PLAY, WAITING_DELETE, DELETE_POST };

enum class RoomProcessState { COMPLETE, PROCESSING };

enum class RoomTaskType { NONE, JOIN, DELETE_USER, READY, KICK, START, GIVEUP };

enum class LifeState { NONE, ACTIVE, DISCONNECT_PENDING, DISCONNECTING };

enum class ModeState { NONE, LOGIN, LOBBY, ROOM };

enum class EventType { NONE = -1, RIGHT, LEFT, ROTATE, DOWN, DROP, UP, MOVE, FIX, CLEARLINE, ADDLINE, GAMEOVER, GAMEEND, SPAWN };
