#pragma once

enum ErrorCode
{
	SUCCESS = 0,
	SERVER_ERROR = 1,
	INVALID_REQUEST = 2,
	LOGIN_FAILED = 3,
	DUPLICATE_LOGIN_ID = 4,

	ROOM_NOT_FOUND = 10,
	ROOM_FULL = 11,
	ROOM_IN_GAME = 12,
	NOT_FOUND_JOINABLE_ROOM = 13,

	ROOM_NOT_ALL_READY = 20,
	ROOM_NOT_ENOUGH_PLAYERS = 21,
	ROOM_INVALID_PASSWORD = 22,

	PLAYER_NOT_FOUND = 30,
};
