# -------- images --------
DEFAULT_RED = 1
DEFAULT_ORANGE = 2
DEFAULT_YELLOW = 3
DEFAULT_GREEN = 4
DEFAULT_BLUE = 5
DEFAULT_INDIGO = 6
DEFAULT_PURPLE = 7
DEFAULT_GRAY = 15

CANDY_RED = 8
CANDY_ORANGE = 9
CANDY_YELLOW = 10  
CANDY_GREEN = 11
CANDY_BLUE = 12
CANDY_INDIGO = 13
CANDY_PURPLE = 14

# ===== UI Image Keys (1000 ~) =====
UI_BUTTON_LOGIN_IDLE = 1000
UI_BUTTON_LOGIN_HOVER = 1001
UI_BUTTON_LOGIN_PRESS = 1002

UI_SHUTTER = 1003
UI_LOGIN_BUTTON = 1004
UI_LOGIN_LABEL_FRAME = 1005
UI_LOGO = 1006

# -------- sounds --------
BGM_INGAME = 0

EFFECT_BUTTON_HOVER = 1
EFFECT_BUTTON_PRESS = 2
EFFECT_MOVE = 3
EFFECT_FIX = 4
EFFECT_CLEARLINE = 5
EFFECT_ADDLINE = 6
EFFECT_SHUTTER = 7
