# packet_registry.py (예시)

from tetris.net.packet_types import *
from tetris.net.packet_structs import *

PACKET_REGISTRY: dict[int, type] = {
    S2C_ERROR: S2C_ERROR_PACKET,
    # ---- Login ----
    S2C_LOGIN: S2C_LOGIN_PACKET,
    C2S_LOGIN: C2S_LOGIN_PACKET,

    # ---- Message ----
    S2C_MESSAGE: S2C_MESSAGE_PACKET,
    C2S_MESSAGE: C2S_MESSAGE_PACKET,

    # ---- Disconnect ----
    S2C_DISCONNECT: S2C_DISCONNECT_PACKET,
    C2S_DISCONNECT: C2S_DISCONNECT_PACKET,

    # ---- Add Open Room ----
    S2C_ADD_OPEN_ROOM: S2C_ADD_OPEN_ROOM_PACKET,
    C2S_ADD_OPEN_ROOM: C2S_ADD_OPEN_ROOM_PACKET,

    # ---- Add Lock Room ----
    S2C_ADD_LOCK_ROOM: S2C_ADD_LOCK_ROOM_PACKET,
    C2S_ADD_LOCK_ROOM: C2S_ADD_LOCK_ROOM_PACKET,

    # ---- Add User ----
    S2C_ADD_USER: S2C_ADD_USER_PACKET,
    C2S_JOIN_OPEN_ROOM: C2S_JOIN_OPEN_ROOM_PACKET,
    C2S_JOIN_LOCK_ROOM: C2S_JOIN_LOCK_ROOM_PACKET,

    # ---- Delete User ----
    S2C_DELETE_USER: S2C_DELETE_USER_PACKET,
    C2S_DELETE_USER: C2S_DELETE_USER_PACKET,

    # ---- Ready ----
    S2C_READY: S2C_READY_PACKET,
    C2S_READY: C2S_READY_PACKET,

    # ---- Start ----
    S2C_SINGLE_START: S2C_SINGLE_START_PACKET,
    S2C_MULTI_START: S2C_MULTI_START_PACKET,
    C2S_START: C2S_START_PACKET,

    # ---- Kick ----
    S2C_KICK: S2C_KICK_PACKET,
    C2S_KICK: C2S_KICK_PACKET,

    # ---- Move / InGame ----
    C2S_MOVE: C2S_MOVE_PACKET,
    S2C_MOVE: S2C_MOVE_PACKET,
    S2C_SPAWN: S2C_SPAWN_PACKET,
    S2C_GAMEOVER: S2C_GAMEOVER_PACKET,
    S2C_GAMEEND: S2C_GAMEEND_PACKET,
    S2C_CLEARLINE: S2C_CLEARLINE_PACKET,
    S2C_FIX: S2C_FIX_PACKET,
    S2C_ADDLINE: S2C_ADDLINE_PACKET,
    S2C_UPDATE_SCORE: S2C_UPDATE_SCORE_PACKET,
    S2C_MATCH_RECORD: S2C_MATCH_RECORD_PACKET,
    S2C_UPDATE_HOST: S2C_UPDATE_HOST_PACKET,
    C2S_GIVEUP: C2S_GIVEUP_PACKET,
    C2S_REQUEST_ROOM_LIST: C2S_REQUEST_ROOM_LIST_PACKET,
    S2C_ROOM_INFO: S2C_ROOM_INFO_PACKET,
}